@startuml diagram
title Data Pipeline
footer Disponível em <repo>

!includeurl https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml
!includeurl https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml
LAYOUT_LANDSCAPE()



Person(user, "Usuario")
Person(user_business, "Usuario de negócio")

System_Boundary(oltp, "OLTP"){
  Container(frontend,"Frontend","Angular")
  Container(api, "API","Java")
  ContainerDb(db, "Database", "Oracle")
}

System_Boundary(data_source,"fontes de dados externas"){
 Container(ibge,"Api IBGE")
 ContainerDb(correrio, "geo","csv")
 ContainerDb(erp,"ERP","DB2","SAP/PROTHEUS")
 ContainerQueue(iot, "sensores","Armazem de distribuição")
 Container(scrapping,"web scrapping")
 Container(pdf,"PDF","PDF")  
}

System_Boundary(olap, "OLAP"){
  Container(extraction,"ingestão de dados")
  Container(object_storage, "S3/blob/gcs/minio","object storage")
  ContainerDb(dw, "Datawarehouse", "BigQuery/Snowflake/Redshift/Exadata")
  Container(transformation,"transformação de dados")

  Rel(extraction, dw, "Salvar dados da origem")
  Rel(extraction, object_storage, "Salvar arquivos")
  Rel(dw, transformation, "transformar dados")
  Rel(object_storage, transformation, "transformar dados")

}


System_Boundary(analytics, "analytics") {
Container(dataviz,"powerbi/tableau", "dataviz")
Container(ml,"machine learnig", "predições e segmentações")
}


Rel(user, frontend, "Realizar pedidos")
Rel(user_business, dataviz, "obter insights")



Rel(frontend, api, "Consumir endpoints")
Rel(api, db, "Persistir dados")

Rel(db,extraction, "Carregar dados da origem")
Rel(ibge, extraction, "carregar dados da origem")
Rel(correio, extraction, "carregar dados da origem")
Rel(erp, extraction, "carregar dados da origem")
Rel(iot, extraction, "carregar dados da origem")
Rel(scrapping, extraction, "carregar dados da origem")
Rel(pdf, extraction, "carregar dados da origem")
Rel(dw, dataviz, "alimentar dados dashboard e insights")

BiRel(dw,ml,"treinar modelo de machine learning")


@enduml